/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionTrackerRouteImport } from './routes/action-tracker'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagingRouteImport } from './routes/packaging'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RootCauseRouteImport } from './routes/root-cause'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as ComplaintsComplaintIdRouteImport } from './routes/complaints.$complaintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionTrackerRoute = ActionTrackerRouteImport.update({
  id: '/action-tracker',
  path: '/action-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingRoute = PackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RootCauseRoute = RootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsComplaintIdRoute = ComplaintsComplaintIdRouteImport.update({
  id: '/complaints/$complaintId',
  path: '/complaints/$complaintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-tracker': typeof ActionTrackerRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packaging': typeof PackagingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/root-cause': typeof RootCauseRoute
  '/settings': typeof SettingsRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-tracker': typeof ActionTrackerRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packaging': typeof PackagingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/root-cause': typeof RootCauseRoute
  '/settings': typeof SettingsRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints': typeof ComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-tracker': typeof ActionTrackerRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packaging': typeof PackagingRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/root-cause': typeof RootCauseRoute
  '/settings': typeof SettingsRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-tracker'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/packaging'
    | '/recommendations'
    | '/register'
    | '/reports'
    | '/root-cause'
    | '/settings'
    | '/complaints/$complaintId'
    | '/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-tracker'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/packaging'
    | '/recommendations'
    | '/register'
    | '/reports'
    | '/root-cause'
    | '/settings'
    | '/complaints/$complaintId'
    | '/complaints'
  id:
    | '__root__'
    | '/'
    | '/action-tracker'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/packaging'
    | '/recommendations'
    | '/register'
    | '/reports'
    | '/root-cause'
    | '/settings'
    | '/complaints/$complaintId'
    | '/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionTrackerRoute: typeof ActionTrackerRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PackagingRoute: typeof PackagingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  RootCauseRoute: typeof RootCauseRoute
  SettingsRoute: typeof SettingsRoute
  ComplaintsComplaintIdRoute: typeof ComplaintsComplaintIdRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-tracker': {
      id: '/action-tracker'
      path: '/action-tracker'
      fullPath: '/action-tracker'
      preLoaderRoute: typeof ActionTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging': {
      id: '/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof PackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-cause': {
      id: '/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof RootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$complaintId': {
      id: '/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof ComplaintsComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionTrackerRoute: ActionTrackerRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PackagingRoute: PackagingRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  RootCauseRoute: RootCauseRoute,
  SettingsRoute: SettingsRoute,
  ComplaintsComplaintIdRoute: ComplaintsComplaintIdRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
